version: '3'
services:
  restAssuredTestNG:
    image: 'sdasa/restatestng'
    #container_name: 'restAssuredTestNG'
    tty: false
    stdin_open: false
    env_file:
      - ./configurations.env
    volumes:
      - ${RESULTS_ARCHIVE}:/home/das/restAssuredTestNG/resultsArchive